services:
  db:
    image: mariadb:11.7-rc
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./greenhouse/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306" # changing 3306 on host machine to 3307
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "db", "--password=admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  greenhouse:
    build:
      context: .
      dockerfile: greenhouse/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/bluebell
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=nimda
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-staging}
    depends_on:
      db:
        condition: service_healthy

  sepal:
    build:
      context: .
      dockerfile: flower/sepal/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      greenhouse:
        condition: service_started

  petal:
    build:
      context: .
      dockerfile: flower/petal/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      greenhouse:
        condition: service_started
volumes:
  mariadb-data:
