module com.bluebell.processing {
	//	auto-generated by ApiExamplesProcessor
	exports com.bluebell.processing.api.examples;
    requires com.google.auto.service;
    requires com.squareup.javapoet;
    requires org.slf4j;
    requires com.fasterxml.jackson.databind;
    requires static lombok;
    requires java.compiler;
    requires io.swagger.v3.oas.annotations;
    requires com.bluebell.platform;
    requires org.apache.commons.lang3;
}
