name: Bug Report
description: Unexpected program behaviour that requires code correction
labels: ["bug", "needs triage"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure that this bug is a genuine one and not a duplicate of an existing issue or feature request.
      options:
        - label: This is not a **[duplicate](https://github.com/sPrizio/bluebell/issues)** of an existing issue
          required: true
        - label: This is not a **[question](https://github.com/sPrizio/bluebell/discussions)**
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: Short explanation of what you were going to do, what went wrong and what was supposed to happen.
      placeholder: |
        I clicked a button and the page threw my computer out of the window
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Every action that was taken, which lead to the bug.
      placeholder: |
        1. Open bluebell
        2. Click button
        3. Computer was gone
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Anything noteworthy that you think might be useful for the team to know
  - type: markdown
    attributes:
      value: |
        ---
        #### Thank you for taking the time to fill out this bug report.