name: Bug Report
description: Unexpected program behaviour that requires code correction
labels: ["bug", "needs triage"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure that our bug report form is appropriate for you.
      options:
        - label: This is not a **[duplicate](https://github.com/sPrizio/bluebell/issues)** of an existing issue
          required: true
        - label: This is not a **[question](https://github.com/sPrizio/bluebell/discussions)**
          required: true
  - type: dropdown
    id: version
    attributes:
      label: ASF version
      description: If you're using a different version than the current stable or pre-release, ensure that your bug report is reproducible on one of the below.
      options:
        - Latest stable release
        - Latest pre-release
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Short explanation of what you were going to do, what did you want to accomplish?
      placeholder: |
        I clicked a button and the page threw my computer out of the window
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: |
        My computer should still be in front of me. I don't know how I am typing this
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happened instead?
      placeholder: |
        My computer fell three stories.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Every action that happened, which leads to the bug.
      placeholder: |
        1. Open bluebell
        2. Click button
        3. Computer was gone
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Everything else you consider worthy that we didn't ask for.
  - type: markdown
    attributes:
      value: |
        ---
        #### Thank you for taking the time to fill out this bug report.