name: ✨ Enhancement idea
description: General idea for improving the project
labels: ["enhancement", "needs triage"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure that our enhancement idea form is appropriate for you.
      options:
        - label: This is not a **[duplicate](https://github.com/sPrizio/bluebell/issues)** of an existing issue
          required: true
        - label: I believe that my idea falls into bluebell's scope and should be offered as part of bluebell built-in functionality
          required: true
  - type: textarea
    id: enhancement-purpose
    attributes:
      label: Enhancement purpose
      description: |
        Purpose of the enhancement - if it solves some problem, precise in particular which. If it benefits the program in some other way, precise in particular why.
        Present the underlying reason why this enhancement makes sense, and what is the context of it.
      placeholder: |
        My broker isn't supported and I would like to see this integration become possible
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What would you like to see as a solution to the purpose specified by you above?
      placeholder: |
        Just make it work, right?
    validations:
      required: true
  - type: textarea
    id: why-existing-not-sufficient
    attributes:
      label: Why currently available solutions are not sufficient?
      description: |
        Evaluate the existing solutions in regards to your requirements.
        If something you're suggesting is already possible, then explain to us why the currently available solutions are not sufficient.
        If it's not possible yet, then explain to us why it should be.
      placeholder: |
        I don't like manually importing my account and trade information, automation would make it far better and make me give you thousands of dollars
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Everything else you consider worthy that we didn't ask for.
  - type: markdown
    attributes:
      value: |
        ---
        #### Thank you for taking the time to fill out this enhancement idea.