name: Feature/Enhancement Request
description: General idea for improving the project
labels: ["enhancement", "needs triage"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure that this feature request is suitable for bluebell and has not already been requested.
      options:
        - label: This is not a **[duplicate](https://github.com/sPrizio/bluebell/issues)** of an existing issue
          required: true
        - label: I believe that my idea falls into bluebell's scope and should be offered as part of bluebell built-in functionality
          required: true
  - type: textarea
    id: enhancement-purpose
    attributes:
      label: Feature Description
      description: |
        Describe the purpose of this feature, what it should do and why you think it would be useful for the system.
      placeholder: |
        My broker isn't supported and I would like to see this integration become possible
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Based on what you said above, how would you like this feature to work/be presented to the user?
      placeholder: |
        Just make it work, right?
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Anything noteworthy that you think might be useful for the team to know.
  - type: markdown
    attributes:
      value: |
        ---
        #### Thank you for taking the time to fill out this enhancement idea.