name: Wiki suggestion
description: All issues related to the wiki documentation, mainly corrections and ideas
labels: ["documentation", "bluebell", "assistance", "needs triage"]
body:
  - type: input
    id: wiki-page
    attributes:
      label: Wiki page
      description: |
        If this is a suggestion regarding an existing wiki page, please link it for reference.
        If the wiki page doesn't exist, suggest its title.
      placeholder: https://github.com/sPrizio/bluebell/wiki/???
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: The issue
      description: |
        Please specify your issue in regards to our wiki documentation.
        If you're reporting a mistake/correction, state what is wrong.
        If you're suggesting an idea, please provide details.
      placeholder: |
        As of today, the wiki doesn't explain how to trade perfectly and make millions of dollars.
    validations:
      required: true
  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested improvement
      description: |
        The new or corrected text that would satisfy your issue stated above.
        You may use **[markdown](https://guides.github.com/features/mastering-markdown)** for formatting.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Anything noteworthy that you think might be useful for the team to know.
  - type: markdown
    attributes:
      value: |
        ---
        #### Thank you for taking the time to fill out this wiki suggestion.