import type {Metadata} from "next";
import "./globals.css";
import SidebarNavigation from "@/components/Navigation/SidebarNavigation";
import {Inter as FontSans} from "next/font/google"
import {cn} from "@/lib/utils";
import React from "react";
import {resolveIcon} from "@/lib/services";
import {Icons} from "@/lib/enums";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const linkStyles = "h-6 w-6 flex-shrink-0";
const links = [
  {
    label: 'Trading Accounts',
    href: "/",
    icon: resolveIcon(Icons.TradingAccounts, linkStyles)
  },
  {
    label: "Account Overview",
    href: "/dashboard",
    icon: resolveIcon(Icons.AccountOverview, linkStyles),
  },
  {
    label: "My Profile",
    href: "/profile",
    icon: resolveIcon(Icons.UserProfile, linkStyles),
  },
  {
    label: "Market News",
    href: "/market-news",
    icon: resolveIcon(Icons.MarketNews, linkStyles),
  },
  {
    label: "Performance",
    href: "/performance",
    icon: resolveIcon(Icons.Performance, linkStyles),
  },
  {
    label: "Logout",
    href: "/logout",
    icon: resolveIcon(Icons.Logout, linkStyles),
  },
];

/**
 * The root layout design
 *
 * @param children page info
 * @author Stephen Prizio
 * @version 0.0.1
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={cn("min-h-screen font-sans antialiased text-slate-600 bg-neutral-100 tracking-tighter", fontSans.variable)}>
      <div className={"flex flex-row"}>
        <div className={""}>
          <SidebarNavigation variant={'primary'} links={links} />
        </div>
        <div className={"flex-1 flex items-start justify-center"}>
          <div className={"w-5/6 lg:w-3/5 min-h-5/6 flex flex-col items-start py-8"}>
            {children}
          </div>
        </div>
      </div>
      </body>
    </html>
  );
}
