import type {Metadata} from "next";
import "./globals.css";
import SidebarNavigation from "@/components/Navigation/SidebarNavigation";
import {Inter as FontSans} from "next/font/google"
import {cn} from "@/lib/utils";
import {IconArrowLeft, IconBrandTabler, IconSettings, IconUserBolt} from "@tabler/icons-react";
import React from "react";
import PageHeaderSection from "@/components/Section/PageHeaderSection";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const linkStyles = "h-6 w-6 flex-shrink-0";
const links = [
  {
    label: 'Trading Accounts',
    href: "/",
    icon: <IconBrandTabler className={linkStyles} />
  },
  {
    label: "Account Overview",
    href: "/dashboard",
    icon: (
      <IconBrandTabler className={linkStyles} />
    ),
  },
  {
    label: "My Profile",
    href: "/profile",
    icon: (
      <IconUserBolt className={linkStyles} />
    ),
  },
  {
    label: "Market News",
    href: "/market-news",
    icon: (
      <IconSettings className={linkStyles} />
    ),
  },
  {
    label: "Performance",
    href: "/performance",
    icon: (
      <IconSettings className={linkStyles} />
    ),
  },
  {
    label: "Logout",
    href: "/logout",
    icon: (
      <IconArrowLeft className={linkStyles} />
    ),
  },
];

/**
 * The root layout design
 *
 * @param children page info
 * @author Stephen Prizio
 * @version 0.0.1
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased text-slate-600 tracking-tighter", fontSans.variable)}>
      <div className={"flex flex-row"}>
        <div className={""}>
          <SidebarNavigation variant={'primary'} links={links} />
        </div>
        <div className={"flex-1 flex items-start justify-center"}>
          <div className={"w-5/6 lg:w-3/5 min-h-5/6 flex items-start py-8"}>
            <PageHeaderSection title={''} subtitle={''} icon={null} />
            {children}
          </div>
        </div>
      </div>
      </body>
    </html>
  );
}
