import type { Metadata } from "next";
import "./globals.css";
import SidebarNavigation from "@/components/Navigation/SidebarNavigation";
import { Inter as FontSans } from "next/font/google"
import {cn} from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased text-slate-600 tracking-tighter", fontSans.variable)}>
      <div className={"flex flex-row"}>
        <div className={"mr-12"}>
          <SidebarNavigation variant={'primary'} />
        </div>
        <div className={"flex-1"}>
          {children}
        </div>
      </div>
      </body>
    </html>
  );
}
