name: bluebell CI / CD
on:
  pull_request:
    branches:
      - '**'
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      env:
        description: "Target environment for the deployment pipeline"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: "[bluebell] - Checkout Repo"
        uses: actions/checkout@v4

      - name: "[greenhouse] - Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: "[flower] - Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: './flower/sepal/package-lock.json'

      - name: "[greenhouse] - Build & Test"
        run: mvn clean package -DskipTests=true
        working-directory: './greenhouse'

      - name: "[sepal] - Install Dependencies"
        run: npm ci
        working-directory: './flower/sepal'

      - name: "[sepal] - Build"
        run: npm run build --if-present
        working-directory: './flower/sepal'

      - name: "[petal] - Install Dependencies"
        run: npm ci
        working-directory: './flower/petal'

      - name: "[petal] - Build"
        run: npm run build --if-present
        working-directory: './flower/petal'

  test:
    runs-on: ubuntu-22.04
    needs: build
    env:
      TARGET_ENV: ${{ github.event.inputs.env || (
        github.ref == 'refs/heads/main'   && 'prod'    ||
        github.ref == 'refs/heads/staging' && 'staging' ||
        'dev'
        ) }}
      UPPER_ENV: ${{ github.event.inputs.env || (
        github.ref == 'refs/heads/main'   && 'PROD'    ||
        github.ref == 'refs/heads/staging' && 'STAGING' ||
        'DEV'
        ) }}
    steps:
      - name: "[bluebell] - Checkout Repo"
        uses: actions/checkout@v4

      - name: "[greenhouse] - Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: "[greenhouse] - Generate .env "
        run: |
          cat > .env <<EOF
          EMAIL_APP_USERNAME=${{ secrets[ format('{0}_EMAIL_APP_USERNAME', env.UPPER_ENV) ] }}
          EMAIL_APP_PASSWORD=${{ secrets[ format('{0}_EMAIL_APP_PASSWORD', env.UPPER_ENV) ] }}
          EMAIL_APP_SENDER=${{ secrets[ format('{0}_EMAIL_APP_SENDER', env.UPPER_ENV) ] }}
          EMAIL_APP_RECIPIENT=${{ secrets[ format('{0}_EMAIL_APP_RECIPIENT', env.UPPER_ENV) ] }}
          EOF
        working-directory: './greenhouse'

      - name: "[greenhouse] - Test"
        run: mvn test
        working-directory: './greenhouse'

  deploy:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    needs: test
    steps:
      - name: "[bluebell] - Checkout Repo"
        uses: actions/checkout@v4

      - name: "[greenhouse] - Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: "[flower] - Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: './flower/sepal/package-lock.json'

      - name: "[bluebell] - Deploy"
        run: echo "Deploying bluebell"
        # Add actual deployment commands here
