name: bluebell CI / CD
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: "[bluebell] - Checkout Repo"
        uses: actions/checkout@v4

      - name: "[greenhouse] - Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: "[flower] - Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: "[greenhouse] - Build & Test"
        run: mvn clean package
        working-directory: './greenhouse'

      - name: "[sepal] - Install Dependencies"
        run: npm ci
        working-directory: './flower/sepal'

      - name: "[sepal] - Build"
        run: npm run build --if-present
        working-directory: './flower/sepal'

  deploy:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - name: "[bluebell] - Checkout Repo"
        uses: actions/checkout@v4

      - name: "[greenhouse] - Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: "[flower] - Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: "[bluebell] - Deploy"
        run: echo "Deploying bluebell"
        # Add actual deployment commands here
